require "prototypes/categories"
require "prototypes/vanilla-overrides"

require "prototypes/buildings"
require "prototypes/hotkeys"
require "prototypes/items"
require "prototypes/recipes"
require "prototypes/resources"
require "prototypes/sounds"
require "prototypes/tools"
